# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WvbVYRCZHwtUNk_WNelMzXUps80AUuvG
"""

import pandas  as pd
df = pd.DataFrame({ 'Ism': [ 'Nurilloh' , 'Muhsinjon', 'Boynazar', 'Alijon', 'Javohir', 'Muhammadsher', 'Asrorbek', 'Tolibjon', 'Mardonbek', 'Ikromjon', ],
                   'Familiya':[ 'Aminjonov', 'Yusufjonov', 'Toxtasinov', 'Bekmirzayev', 'Abduqodirov', 'Inomov', 'Ubaydullayev', 'Rayimjonov', 'Tursunov', 'Tursunov'],
                    'Yoshi': ['19', '19', '19', '19', '19', '19', '19', '19', '19', '19'],
                    'Kursi': ['2', '2', '2', '2', '2', '2', '2', '2', '2', '2'],
                    })
print(df)

df.to_excel( 'hisobot.xlsx', index=False, sheet_name='Sheet1')